name: "grusp"
on: ["push", "pull_request"]
env:
  DO_NOT_TRACK: true
jobs:
  build:
    runs-on: go # scelta del sdk
    steps:
      - name: build
        with:
          action: "demo:build" # azione da esguire
          registry-creds: regcred
  publish:
    needs: [build] # dipendenze tra job
    runs-on: go
    steps:
      - name: publish
        with:
          action: "demo:publish"
          registry-creds: regcred # credenziali da k8s
  # non parte della vera ci/cd, solo per la demo
  deploy:
    needs: [publish] # dipendenze tra job
    runs-on: go
    steps:
      - name: deploy
        with:
          action: "demo:deploy"
          registry-creds: regcred # credenziali da k8s
        env:
          HELLO_REPLICAS: ${HELLO_REPLICAS:-"2"}
