---
kind: ConfigMap
apiVersion: v1
metadata:
  name: installer-scripts-v1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dind-config-v1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: buildkit-config-v1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: dagger-config-v1
